#
# MoreFish Configuration by elsiff
#
# Wiki: https://github.com/elsiff/MoreFish/wiki

shop-allow-click-id:
  - '1:0'
rank-reward:
  "1":
    string-action:
      - '[CMD]say hello'
  "2":
    string-action:
      - '[CMD]say hello'
version: 210

general:
  locale: 'en'
  auto-start: false
  use-boss-bar: true
  only-for-contest: false
  no-fishing-unless-contest: false
  contest-disabled-worlds: []
  replace-only-fish: false
  save-records: false

auto-running:
  enable: false
  required-players: 5
  timer: 300
  # HH:mm (H: 0-23, m: 0-59)
  start-time:
  - "09:00"
  - "11:30"
  - "14:00"
  - "18:00"
  - "21:00"

fish-shop:
  enable: true
  multiplier: 0.1
  round-decimal-points: true

# -- Announcement Value --
# '-1' means server broadcast
# '0' is only for the catcher
# Positive number means the block radius of announcing messages
messages:
  announce-catch: -1
  announce-new-1st: -1
  broadcast-start: true
  broadcast-stop: true
  show-top-on-ending: true
  contest-bar-color: 'blue'
  top-number: 3
